import fs from 'fs';
import path from 'path';

export interface PlaceholderEntry {
  key: string;
  placeholder: string;
}

export function parseVaultForPlaceholders(content: string): PlaceholderEntry[] {
  const entries: PlaceholderEntry[] = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    entries.push({ key, placeholder: value });
  }
  return entries;
}

export function generatePlaceholderFile(entries: PlaceholderEntry[]): string {
  const lines: string[] = [
    '# .env.example — auto-generated by envault placeholder',
    '# Do not store real secrets here.',
    '',
  ];
  for (const { key, placeholder } of entries) {
    const masked = placeholder.length > 0 ? '<' + key.toLowerCase() + '>' : '';
    lines.push(`${key}=${masked}`);
  }
  return lines.join('\n') + '\n';
}

export function runPlaceholder(vaultPath: string, outputPath: string): void {
  if (!fs.existsSync(vaultPath)) {
    console.error(`Vault file not found: ${vaultPath}`);
    process.exit(1);
  }
  const content = fs.readFileSync(vaultPath, 'utf-8');
  const entries = parseVaultForPlaceholders(content);
  if (entries.length === 0) {
    console.log('No entries found in vault.');
    return;
  }
  const output = generatePlaceholderFile(entries);
  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`Placeholder file written to ${outputPath} (${entries.length} keys).`);
}
