import * as fs from "fs";
import * as path from "path";
import { VAULT_FILE } from "../constants";

export interface TemplateEntry {
  key: string;
  description?: string;
  required: boolean;
  defaultValue?: string;
}

export function parseVaultKeysForTemplate(vaultPath: string): string[] {
  if (!fs.existsSync(vaultPath)) return [];
  const content = fs.readFileSync(vaultPath, "utf-8");
  const keys: string[] = [];
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex > 0) {
      keys.push(trimmed.substring(0, eqIndex).trim());
    }
  }
  return keys;
}

export function generateTemplate(entries: TemplateEntry[]): string {
  const lines: string[] = [
    "# .env.template — generated by envault",
    "# Fill in required values before running 'envault import'",
    "",
  ];
  for (const entry of entries) {
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }
    const required = entry.required ? "# [REQUIRED]" : "# [OPTIONAL]";
    lines.push(required);
    const value = entry.defaultValue !== undefined ? entry.defaultValue : "";
    lines.push(`${entry.key}=${value}`);
    lines.push("");
  }
  return lines.join("\n");
}

export function runTemplate(
  vaultPath: string = VAULT_FILE,
  outputPath: string = ".env.template"
): void {
  const keys = parseVaultKeysForTemplate(vaultPath);
  if (keys.length === 0) {
    console.log("No keys found in vault. Nothing to template.");
    return;
  }
  const entries: TemplateEntry[] = keys.map((key) => ({
    key,
    required: true,
  }));
  const content = generateTemplate(entries);
  fs.writeFileSync(outputPath, content, "utf-8");
  console.log(`Template written to ${outputPath} with ${keys.length} key(s).`);
}
