import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  parseVaultKeysForTemplate,
  generateTemplate,
  runTemplate,
  TemplateEntry,
} from "./template";

function writeTmp(name: string, content: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "envault-template-"));
  const filePath = path.join(dir, name);
  fs.writeFileSync(filePath, content, "utf-8");
  return filePath;
}

describe("parseVaultKeysForTemplate", () => {
  it("returns keys from a vault file", () => {
    const vault = writeTmp("vault.env", "API_KEY=encrypted1\nDB_URL=encrypted2\n");
    const keys = parseVaultKeysForTemplate(vault);
    expect(keys).toEqual(["API_KEY", "DB_URL"]);
  });

  it("ignores comment lines", () => {
    const vault = writeTmp("vault.env", "# comment\nSECRET=enc\n");
    const keys = parseVaultKeysForTemplate(vault);
    expect(keys).toEqual(["SECRET"]);
  });

  it("returns empty array if file does not exist", () => {
    const keys = parseVaultKeysForTemplate("/nonexistent/path.env");
    expect(keys).toEqual([]);
  });
});

describe("generateTemplate", () => {
  it("generates template with required keys", () => {
    const entries: TemplateEntry[] = [
      { key: "API_KEY", required: true, description: "API access key" },
      { key: "DB_URL", required: false, defaultValue: "localhost" },
    ];
    const output = generateTemplate(entries);
    expect(output).toContain("API_KEY=");
    expect(output).toContain("DB_URL=localhost");
    expect(output).toContain("# [REQUIRED]");
    expect(output).toContain("# [OPTIONAL]");
    expect(output).toContain("# API access key");
  });

  it("includes header comment", () => {
    const output = generateTemplate([]);
    expect(output).toContain("# .env.template — generated by envault");
  });
});

describe("runTemplate", () => {
  it("writes a template file from vault keys", () => {
    const vault = writeTmp("vault.env", "TOKEN=enc1\nPORT=enc2\n");
    const outDir = fs.mkdtempSync(path.join(os.tmpdir(), "envault-out-"));
    const outPath = path.join(outDir, ".env.template");
    runTemplate(vault, outPath);
    expect(fs.existsSync(outPath)).toBe(true);
    const content = fs.readFileSync(outPath, "utf-8");
    expect(content).toContain("TOKEN=");
    expect(content).toContain("PORT=");
  });

  it("logs a message if vault has no keys", () => {
    const vault = writeTmp("vault.env", "# only comments\n");
    const outPath = path.join(os.tmpdir(), ".env.template.empty");
    const spy = jest.spyOn(console, "log").mockImplementation(() => {});
    runTemplate(vault, outPath);
    expect(spy).toHaveBeenCalledWith(expect.stringContaining("No keys found"));
    spy.mockRestore();
  });
});
